### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Zumbalamambo** [uoip/g2opy#41]
I'm not able to build g20. Im getting the following error

```

> Traceback (most recent call last):
>   File "setup.py", line 43, in <module>
>     long_description=""
>   File "C:\Users\stanl\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\Users\stanl\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Users\stanl\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\Users\stanl\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "setup.py", line 25, in run
>     assert len(lib_file) == 1
> AssertionError
> 

```

**Comment by AndreaFinazzi** [comment]
Be sure to have one, and only one, file matching the expression "g2o*.so" in the ./lib/ folder.
