### ISSUE TITLE
cannot import g2o in my intepretor

### ISSUE THREAD

**Issue by shaoxh** [uoip/g2opy#50]
I have finish the final installation: "python setup.py install". 
The .so file have been added to the packages. 
But when I import g2o, there is error like this: "malloc(): memory corruption".
When I debug an example called ba_demo.py, error message like this:  
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/python3/dist-packages/g2o.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cs_di_schol
python-BaseException

But the thing is ".so" file have been sucessfully achieved. All is right. 
I have no idea where this error come from.

I realize nobody ask this kind question. Is this because this project no longer fit to the current g2o codes?

**Comment by shaoxh** [comment]
I am using python 3.6, eigen 3.39
